INSERT INTO XUSER(EMAIL) VALUES('e1@google.com');
INSERT INTO XUSER(EMAIL) VALUES('e2@naver.com');
INSERT INTO XUSER(EMAIL) VALUES('e3@daum.com');

INSERT INTO XBOARD(ID, WRITER, TITLE, CONTENT, REG_DATE, HIT_COUNT) VALUES(XBOARD_SEQ.NEXTVAL, 'W1', 'T1', 'C1', SYSDATE, 0);
INSERT INTO XBOARD(ID, WRITER, TITLE, CONTENT, REG_DATE, HIT_COUNT) VALUES(XBOARD_SEQ.NEXTVAL, 'W2', 'T2', 'C2', SYSDATE, 0);
INSERT INTO XBOARD(ID, WRITER, TITLE, CONTENT, REG_DATE, HIT_COUNT) VALUES(XBOARD_SEQ.NEXTVAL, 'W3', 'T3', 'C3', SYSDATE, 0);
INSERT INTO XBOARD(ID, WRITER, TITLE, CONTENT, REG_DATE, HIT_COUNT) VALUES(XBOARD_SEQ.NEXTVAL, 'W4', 'T4', 'C4', SYSDATE, 0);
INSERT INTO XBOARD(ID, WRITER, TITLE, CONTENT, REG_DATE, HIT_COUNT) VALUES(XBOARD_SEQ.NEXTVAL, 'W5', 'T5', 'C5', SYSDATE, 0);
INSERT INTO XBOARD(ID, WRITER, TITLE, CONTENT, REG_DATE, HIT_COUNT) VALUES(XBOARD_SEQ.NEXTVAL, 'W6', 'T6', 'C6', SYSDATE, 0);
INSERT INTO XBOARD(ID, WRITER, TITLE, CONTENT, REG_DATE, HIT_COUNT) VALUES(XBOARD_SEQ.NEXTVAL, 'W7', 'T7', 'C7', SYSDATE, 0);
INSERT INTO XBOARD(ID, WRITER, TITLE, CONTENT, REG_DATE, HIT_COUNT) VALUES(XBOARD_SEQ.NEXTVAL, 'W8', 'T8', 'C8', SYSDATE, 0);
INSERT INTO XBOARD(ID, WRITER, TITLE, CONTENT, REG_DATE, HIT_COUNT) VALUES(XBOARD_SEQ.NEXTVAL, 'W9', 'T9', 'C9', SYSDATE, 0);
INSERT INTO XBOARD(ID, WRITER, TITLE, CONTENT, REG_DATE, HIT_COUNT) VALUES(XBOARD_SEQ.NEXTVAL, 'W10', 'T10', 'C10', SYSDATE, 0);
INSERT INTO XBOARD(ID, WRITER, TITLE, CONTENT, REG_DATE, HIT_COUNT) VALUES(XBOARD_SEQ.NEXTVAL, 'W11', 'T11', 'C11', SYSDATE, 0);
